"""Build six concise bilingual static pages."""
from pathlib import Path
from html import escape as e
import json
ROOT=Path(__file__).resolve().parents[1]
SCHOLAR='https://scholar.google.com/citations?user=uld736gAAAAJ'
PROFILE='https://new.skoltech.ru/en/persons/ilya-chepkasov'
def t(ru,en,tag='span',cls=''):
    return f'<{tag} class="{cls}" data-ru="{e(ru,quote=True)}" data-en="{e(en,quote=True)}">{e(ru)}</{tag}>'
def link(url,ru,en,cls='text-link'):
    ext=' target="_blank" rel="noopener noreferrer"' if url.startswith('https:') else ''
    return f'<a class="{cls}" href="{e(url,quote=True)}"{ext}>{t(ru,en)} <span aria-hidden="true">↗</span></a>'
NAV=[('index.html','Главная','Home'),('research.html','Исследования','Research'),('publications.html','Публикации','Publications'),('activities.html','Деятельность','Activities'),('cv.html','Биография','Biography'),('contact.html','Контакты','Contact')]
def page(file,ru,en,body,home=False):
    nav=''.join(f'<a href="{f}"'+(' aria-current="page"' if f==file else '')+f'>{t(r,v)}</a>' for f,r,v in NAV)
    head=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Илья Чепкасов — старший научный сотрудник Сколтеха. Вычислительное материаловедение, нанокатализ и материалы для энергетики."><title>{ru} — Илья Чепкасов</title><link rel="icon" href="assets/images/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/styles.css"><script src="assets/js/publications-data.js" defer></script><script src="assets/js/main.js" defer></script></head><body data-title-ru="{ru} — Илья Чепкасов" data-title-en="{en} — Ilya Chepkasov" class="{'home' if home else 'inner'}"><a class="skip" href="#main">{t('К содержанию','Skip to content')}</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html"><span class="brand-mark" aria-hidden="true">IC<span>·</span></span><span class="brand-name">{t('Илья Чепкасов','Ilya Chepkasov')}</span></a><button id="menu-toggle" class="menu-toggle" aria-controls="nav" aria-expanded="false">{t('Меню','Menu')}</button><nav id="nav" aria-label="Навигация" data-aria-ru="Навигация" data-aria-en="Main navigation">{nav}</nav><div class="language" role="group" aria-label="Язык / Language"><button data-lang="ru" aria-pressed="true">RU</button><span>/</span><button data-lang="en" aria-pressed="false">EN</button></div></div></header>'''
    footer=f'''<footer><div class="container footer-inner"><span>© 2026 {t('Илья Чепкасов','Ilya Chepkasov')}</span><div class="footer-links">{link(SCHOLAR,'Google Scholar','Google Scholar')}{link('https://orcid.org/0000-0001-8376-2999','ORCID','ORCID')}<a href="mailto:I.Chepkasov@skoltech.ru">Email ↗</a></div></div></footer></body></html>'''
    (ROOT/file).write_text(head+f'<main id="main">{body}</main>'+footer,encoding='utf-8',newline='\n')
def heading(ru,en,extra=''):
    return f'<section class="page-head container">{t(ru,en,"h1")}{extra}</section>'
FIELDS=[
('Нанокатализ','Nanocatalysis','Биметаллические частицы и структуры ядро–оболочка; адсорбция и каталитические свойства.','Bimetallic and core–shell nanoparticles; adsorption and catalytic properties.','10.1016/j.mtener.2025.102130'),
('Материалы для аккумуляторов','Battery materials','Углеродные и органические аноды, твердотельные электролиты, ионная проводимость.','Carbon and organic anodes, solid-state electrolytes, ionic conductivity.','10.1016/j.pmatsci.2026.101713'),
('Двумерные материалы','Two-dimensional materials','Графен, MoS₂, гетероструктуры: устойчивость и электронные свойства.','Graphene, MoS₂ and heterostructures: stability and electronic properties.','10.1021/acs.jpcc.2c03749'),
('Термоэлектрики','Thermoelectrics','Влияние легирования и дефектов на механические свойства PbTe.','Effects of doping and defects on the mechanical properties of PbTe.','10.1039/d5ta00823a'),
('Атомистическое моделирование','Atomistic modeling','DFT, молекулярная динамика, предсказание структуры, потенциалы машинного обучения.','DFT, molecular dynamics, structure prediction, machine-learning interatomic potentials.','10.1039/d5ta00823a')]
AREA_IDS=['catalysis','batteries','2d','thermoelectrics','modeling']
chips=''.join(f'<a href="research.html?area={area}">{t(ru,en)}<span aria-hidden="true">↗</span></a>' for area,(ru,en,*_) in zip(AREA_IDS,FIELDS[:4]))
home=f'''<section class="hero container"><div class="hero-copy">{t('Вычислительное материаловедение','Computational materials science','p','eyebrow')}<h1>{t('Илья','Ilya')}<br>{t('Чепкасов','Chepkasov')}</h1><div class="hero-role">{t('Старший научный сотрудник · Сколтех','Senior Research Scientist · Skoltech','p')}{t('Кандидат физико-математических наук','PhD in condensed matter physics','p')}</div><div class="research-chips">{chips}</div><p class="hero-methods">DFT · MD · Machine Learning</p><div class="hero-actions">{link('publications.html','Публикации','Publications','button')}{link(SCHOLAR,'Google Scholar','Google Scholar')}</div></div><figure class="portrait"><img src="assets/images/portrait.jpg" alt="Илья Чепкасов" data-alt-ru="Илья Чепкасов" data-alt-en="Ilya Chepkasov" width="640" height="640" fetchpriority="high"></figure></section>'''
page('index.html','Главная','Home',home,True)
WORKS=[
('Pt/C','Pt/C','Азотированный углеродный носитель','Nitrogen-doped carbon support','Small · 2025','10.1002/smll.202510144','pt-carbon.jpg','Графическая аннотация работы о Pt/C','Graphical abstract of the Pt/C study'),
('Органические электроды','Organic electrodes','Полициклические ароматические углеводороды в металл-ионных аккумуляторах.','Polycyclic aromatic hydrocarbons in metal-ion batteries.','Progress in Materials Science · 2026','10.1016/j.pmatsci.2026.101713','battery-review.webp','Схема материалов для металл-ионных аккумуляторов из обзора','Metal-ion battery materials diagram from the review'),
('Монослой V₃S₄','V₃S₄ monolayer','Атомная структура и электронные свойства материала для газовых сенсоров.','Atomic structure and electronic properties of a gas-sensing material.','Nanomaterials · 2022','10.3390/nano12050774','v3s4-monolayer.jpg','Структура, фононы и зонная структура V₃S₄; рисунок 2','V₃S₄ structure, phonons and electronic bands; Figure 2'),
('Дефекты в PbTe','Defects in PbTe','Легирование, химическая связь и механические свойства.','Doping, chemical bonding and mechanical properties.','Journal of Materials Chemistry A · 2025','10.1039/d5ta00823a','pbte-defects.jpg','Дефекты и локализация электронов в PbTe; рисунок 1','Defects and electron localization in PbTe; Figure 1'),
('Моделирование PbTe','Simulating PbTe','DFT и потенциалы машинного обучения для расчета деформации.','DFT and machine-learning potentials for deformation simulations.','Journal of Materials Chemistry A · 2025','10.1039/d5ta00823a','pbte-simulation.png','Моделирование деформации PbTe; рисунок 6','PbTe deformation simulations; Figure 6')]
tabs=''.join(f'<button id="tab-{area}" role="tab" data-area="{area}" aria-controls="panel-{area}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}">{t(ru,en)}<span class="tab-arrow" aria-hidden="true">↗</span></button>' for i,(area,(ru,en,*_)) in enumerate(zip(AREA_IDS,FIELDS)))
panels=[]
catalog=json.loads((ROOT/'assets/data/publications.json').read_text(encoding='utf-8'))
for i,(area,field,work) in enumerate(zip(AREA_IDS,FIELDS,WORKS)):
    ru,en,dr,de,_=field
    wr,we,sr,se,journal,doi,img,ar,ae=work
    image_path='assets/images/'+img
    art='<div class="research-art" aria-hidden="true"></div>' if i==0 else f'<img class="study-image" src="{image_path}" alt="{e(ar)}" data-alt-ru="{e(ar)}" data-alt-en="{e(ae)}" loading="lazy">'
    original=link(image_path,'Оригинал','Original').replace('class="text-link"','class="text-link" data-open-image')
    title=next(record['title'] for record in catalog if record.get('doi','').lower()==doi.lower())
    paper=link('https://doi.org/'+doi,'Публикация','Paper').replace('class="text-link"',f'class="text-link" title="{e(title,quote=True)}"')
    panels.append(f'''<article id="panel-{area}" class="research-panel {'catalysis-panel' if i==0 else ''}" role="tabpanel" aria-labelledby="tab-{area}" tabindex="0" {'' if i==0 else 'hidden'}><div class="study-copy">{t(ru,en,'p','study-area')}{t(wr,we,'h2')}{t(sr,se,'p','study-description')}<div class="study-reference"><span class="visual-journal">{journal}</span>{paper}</div></div><div class="study-visual">{art}</div><div class="study-caption">{t(ar,ae)}{original}</div></article>''')
research=heading('Исследования','Research')+f'''<section class="container research-layout"><div class="research-navigation"><div class="research-tabs" role="tablist" aria-orientation="vertical" aria-label="Направления исследований" data-aria-ru="Направления исследований" data-aria-en="Research areas">{tabs}</div><div class="research-tools">{t('Методы','Methods','h2')}<p>DFT · MD · Machine Learning</p><p>VASP · LAMMPS · USPEX · MLIP</p></div></div><div class="research-stage">{''.join(panels)}</div></section>'''
research+=f'''<dialog id="figure-viewer" aria-labelledby="figure-caption"><div class="viewer-header"><p id="figure-caption"></p><button id="close-figure" type="button">{t('Закрыть','Close')} <span aria-hidden="true">×</span></button></div><img id="figure-original" alt=""></dialog>'''
page('research.html','Исследования','Research',research)
pub=heading('Публикации','Publications',link(SCHOLAR,'Google Scholar','Google Scholar'))
pub+=f'''<section class="container publications-content"><div class="publication-tools"><label class="search-label">{t('Поиск','Search')}<input id="search" type="search" placeholder="Название, автор, журнал или DOI" data-placeholder-ru="Название, автор, журнал или DOI" data-placeholder-en="Title, author, journal or DOI" autocomplete="off"></label><label>{t('Год','Year')}<select id="year"><option value="all" data-ru="Все годы" data-en="All years">Все годы</option></select></label><label>{t('Порядок','Sort by')}<select id="sort"><option value="new" data-ru="Сначала новые" data-en="Newest first">Сначала новые</option><option value="old" data-ru="Сначала ранние" data-en="Oldest first">Сначала ранние</option><option value="title" data-ru="По названию" data-en="Title A–Z">По названию</option><option value="type" data-ru="Сначала обзоры" data-en="Reviews first">Сначала обзоры</option></select></label></div><div class="publication-bar"><div class="type-tabs" role="group" aria-label="Тип публикации" data-aria-ru="Тип публикации" data-aria-en="Publication type"><button data-type="all" aria-pressed="true">{t('Все','All')}</button><button data-type="review" aria-pressed="false">{t('Обзоры','Reviews')}</button><button data-type="article" aria-pressed="false">{t('Статьи','Articles')}</button><button data-type="conference" aria-pressed="false">{t('Конференции','Proceedings')}</button></div><span id="result-count" role="status" aria-live="polite"></span><button id="reset" class="reset">{t('Сбросить','Reset')}</button></div><div id="publication-list"></div><div id="empty" class="empty" hidden>{t('Публикации не найдены.','No publications found.')}</div><noscript><p>Для поиска включите JavaScript. / Enable JavaScript to search.</p></noscript><p class="catalog-note">{t('Резюме и Crossref · Проверено 05.10.2026 · Без автосинхронизации со Scholar','CV and Crossref · Checked Oct 5, 2026 · No Scholar auto-sync')}</p></section>'''
page('publications.html','Публикации','Publications',pub)
TIMELINE=[('2020 —','Сколтех','Skoltech','В Сколтехе с августа 2020 года. Сейчас — старший научный сотрудник.','Joined in August 2020. Currently Senior Research Scientist.'),('2018–2019 · 2021','HZDR, Дрезден','HZDR, Dresden','Приглашенный исследователь; атомистическое моделирование.','Visiting researcher; atomistic simulations.'),('2019–2020','НИТУ МИСИС','NUST MISIS','Приглашенный исследователь лаборатории неорганических наноматериалов.','Visiting researcher, Inorganic Nanomaterials Laboratory.'),('2014–2020','ХГУ им. Н. Ф. Катанова','Katanov Khakas State University','Лаборатория нанофизики (2014–2018); преподавание физики (2014–2020).','Nanophysics Laboratory (2014–2018); teaching physics (2014–2020).'),('2013','Кандидат физико-математических наук','PhD in condensed matter physics','Диссертация: моделирование синтеза наночастиц меди из газовой фазы.','Thesis: simulations of copper nanoparticle synthesis from the gas phase.'),('2005–2010','Образование: физика','Education: physics','ХГУ им. Н. Ф. Катанова, Абакан.','Katanov Khakas State University, Abakan.')]
timeline=''.join(f'<article class="timeline-row"><span class="timeline-date">{date}</span><div>{t(ru,en,"h2")}{t(dr,de,"p")}</div></article>' for date,ru,en,dr,de in TIMELINE)
page('cv.html','Биография','Biography',heading('Биография','Biography',link(PROFILE,'Профиль Сколтеха','Skoltech profile'))+f'<section class="container biography"><div class="timeline">{timeline}</div></section>')
def block(ru,en,dr,de): return f'<article class="activity-block">{t(ru,en,"h2")}{t(dr,de,"p")}</article>'
activities=heading('Научная деятельность','Academic activities')+'<section class="container activity-grid">'
activities+=block('РНФ · 2022–2024','RSF · 2022–2024','Руководитель проекта 22-73-00219: дизайн электролитов для твердотельных аккумуляторов.','PI, project 22-73-00219: design of electrolytes for solid-state batteries.')
activities+=block('DAAD · 2018–2021','DAAD · 2018–2021','Программа «Михаил Ломоносов»: двумерные материалы (2018–2019), аноды для аккумуляторов (2020–2021).','Mikhail Lomonosov program: 2D materials (2018–2019), battery anodes (2020–2021).')
activities+=block('Конференции','Conferences','РОСКАТАЛИЗ (2025), Менделеевский съезд (2024), IUCr (2023). Приглашенный доклад — IMRC, Канкун (2017).','ROSKATALIZ (2025), Mendeleev Congress (2024), IUCr (2023). Invited talk — IMRC, Cancun (2017).')
activities+=block('Рецензирование','Peer review','Journal of Alloys and Compounds; Industrial & Engineering Chemistry Research; Journal of Molecular Liquids; Computational Materials Science.','Journal of Alloys and Compounds; Industrial & Engineering Chemistry Research; Journal of Molecular Liquids; Computational Materials Science.')
activities+=block('Преподавание','Teaching','Физика, ХГУ им. Н. Ф. Катанова (2014–2020).','Physics, Katanov Khakas State University (2014–2020).')
activities+=block('Научные школы','Scientific schools','IFF Spring Schools, Forschungszentrum Jülich: 2014, 2015, 2019.','IFF Spring Schools, Forschungszentrum Jülich: 2014, 2015, 2019.')
page('activities.html','Деятельность','Activities',activities+'</section>')
page('contact.html','Контакты','Contact',heading('Контакты','Contact')+f'<section class="container contact-grid"><div class="contact-main"><a class="email" href="mailto:I.Chepkasov@skoltech.ru">I.Chepkasov@skoltech.ru ↗</a>{t("Сколковский институт науки и технологий","Skolkovo Institute of Science and Technology","h2")}{t("Большой бульвар, 30, стр. 1, Москва, 121205","Bolshoy Boulevard 30, bld. 1, Moscow, 121205","p")}</div><div class="contact-profiles">{link(SCHOLAR,"Google Scholar","Google Scholar")}{link("https://orcid.org/0000-0001-8376-2999","ORCID","ORCID")}{link(PROFILE,"Сколтех","Skoltech")}{link("https://iocd.ru/","Лаборатория IOCD","IOCD Lab")}</div></section>')
print('Built 6 compact bilingual pages')
